frase = 'curso em video python'
#print(frase[3:13]) #IMPRIME SOMENTE OS CARACTERES DA POSIÇÃO 3 A POSIÇÃO 13
#n = frase.find('uma') #ENCONTRA UM ITEM DENTRO DA VARIVAVEL
#n = frase.replace('python', 'java') #TROCA UMA STRING POR OUTRA
#n = frase.split() #FATIA, CRIA UMA LISTA DE TODAS AS PALAVRAS DA STRING DE FORMA SEPARADA
#n = frase.count('o') #CONTA QUANTAS STRINGS SOLICITADAS TEM, CASO CONTA AS LETRAS O
#n = '-'.join(frase)
#n = frase.capitalize() #COLOCA SÓ A PRIMEIRA LETRA DE TODA A STRING EM MAIÚSCULO
#n = len(frase) #INFORMA O TAMANHO DA STRING
#n = frase.strip() #RETIRA TODOS OS ESPAÇOS EXCEDENTES NO INICIO E FINAL DA STRING
#n = frase.rstrip() #RETIRA TODOS OS ESPAÇOS EXCEDENTES A DIREITA DA STRING
#n = frase.lstrip() #RETIRA TODOS OS ESPAÇOS EXCEDENTES A ESQUERDA DA STRING
#n = frase.upper()
#n = frase.title() #COLOCA TODAS AS PRIMEIRAS LETRAS EM MAIÚSCULO
#PODE-SE COMBINAR VÁRIAS FUNÇÕES DENTRO DO COMANDO
#EX. PRINT(FRASE.LOWER().STRIP().CAPITALIZE().COUNT()


#print(n)