a = (input('Digite algo: '))
print('é número? ', a.isnumeric())
print('são letras? ', a.isalpha())
print('é um número decimal? ', a.isdecimal())
print('é letra? ', a.isalpha(), 'e está em caixa alta? ', a.isupper())
print('O tipo primitivo desse valor é ',type(a))
print('Só tem espaços?', a.isspace())
print('É alfanumérico?', a.isalnum())
print('Está em minúscula?', a.islower())
print('Está capitalizado?', a.istitle())